-- R99 Supabase health-check cron
--
-- Run this in Supabase Dashboard > SQL Editor.
-- It checks daily and writes one row only when the latest successful check is
-- at least 5 days old, so the project receives server-side activity even when
-- the Flutter app is closed.

create extension if not exists pg_cron with schema extensions;

create table if not exists public.health_check_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null,
  message text not null,
  source text not null default 'supabase_cron'
);

alter table public.health_check_logs enable row level security;

drop policy if exists "Authenticated users can read health check logs"
  on public.health_check_logs;

create policy "Authenticated users can read health check logs"
  on public.health_check_logs
  for select
  to authenticated
  using (true);

create or replace function public.r99_write_health_check_log()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1
    from public.health_check_logs
    where status = 'success'
      and created_at > now() - interval '5 days'
  ) then
    return;
  end if;

  insert into public.health_check_logs (status, message, source)
  values (
    'success',
    'Supabase cron health check completed successfully.',
    'supabase_cron'
  );
end;
$$;

-- Remove the existing job if you are re-running this script.
select cron.unschedule('r99-health-check-every-5-days')
where exists (
  select 1
  from cron.job
  where jobname = 'r99-health-check-every-5-days'
);

-- Runs daily at 00:00 UTC, but the function writes only once per 5 days.
select cron.schedule(
  'r99-health-check-every-5-days',
  '0 0 * * *',
  $$ select public.r99_write_health_check_log(); $$
);

-- Optional: run once immediately so the app Health Logs page can show data now.
select public.r99_write_health_check_log();
